/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rosist.difunto.modelSbp;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 *
 * @author Administrador
 */

@Getter
@Setter
@ToString
@AllArgsConstructor
@NoArgsConstructor
public class Nicho_n {
	private Cuartel cuartel;
    private Integer fila1;
    private String fila2;
    private Integer col001;
    private Integer col002;
    private Integer col003;
    private Integer col004;
    private Integer col005;
    private Integer col006;
    private Integer col007;
    private Integer col008;
    private Integer col009;
    private Integer col010;
    private Integer col011;
    private Integer col012;
    private Integer col013;
    private Integer col014;
    private Integer col015;
    private Integer col016;
    private Integer col017;
    private Integer col018;
    private Integer col019;
    private Integer col020;
    private Integer col021;
    private Integer col022;
    private Integer col023;
    private Integer col024;
    private Integer col025;
    private Integer col026;
    private Integer col027;
    private Integer col028;
    private Integer col029;
    private Integer col030;
    private Integer col031;
    private Integer col032;
    private Integer col033;
    private Integer col034;
    private Integer col035;
    private Integer col036;
    private Integer col037;
    private Integer col038;
    private Integer col039;
    private Integer col040;
    private Integer col041;
    private Integer col042;
    private Integer col043;
    private Integer col044;
    private Integer col045;
    private Integer col046;
    private Integer col047;
    private Integer col048;
    private Integer col049;
    private Integer col050;
    private Integer col051;
    private Integer col052;
    private Integer col053;
    private Integer col054;
    private Integer col055;
    private Integer col056;
    private Integer col057;
    private Integer col058;
    private Integer col059;
    private Integer col060;
    private Integer col061;
    private Integer col062;
    private Integer col063;
    private Integer col064;
    private Integer col065;
    private Integer col066;
    private Integer col067;
    private Integer col068;
    private Integer col069;
    private Integer col070;
    private Integer col071;
    private Integer col072;
    private Integer col073;
    private Integer col074;
    private Integer col075;
    private Integer col076;
    private Integer col077;
    private Integer col078;
    private Integer col079;
    private Integer col080;
    private Integer col081;
    private Integer col082;
    private Integer col083;
    private Integer col084;
    private Integer col085;
    private Integer col086;
    private Integer col087;
    private Integer col088;
    private Integer col089;
    private Integer col090;
    private Integer col091;
    private Integer col092;
    private Integer col093;
    private Integer col094;
    private Integer col095;
    private Integer col096;
    private Integer col097;
    private Integer col098;
    private Integer col099;
    private Integer col100;
    private Integer col101;
    private Integer col102;
    private Integer col103;
    private Integer col104;
    private Integer col105;
    private Integer col106;
    private Integer col107;
    private Integer col108;
    private Integer col109;
    private Integer col110;
    private Integer col111;
    private Integer col112;
    private Integer col113;
    private Integer col114;
    private Integer col115;
    private Integer col116;
    private Integer col117;
    private Integer col118;
    private Integer col119;
    private Integer col120;
    private Integer col121;
    private Integer col122;
    private Integer col123;
    private Integer col124;
    private Integer col125;
    private Integer col126;
    private Integer col127;
    private Integer col128;
    private Integer col129;
    private Integer col130;
    private Integer col131;
    private Integer col132;
    private Integer col133;
    private Integer col134;
    private Integer col135;
    private Integer col136;
    private Integer col137;
    private Integer col138;
    private Integer col139;
    private Integer col140;
    private Integer col141;
    private Integer col142;
    private Integer col143;
    private Integer col144;
    private Integer col145;
    private Integer col146;
    private Integer col147;
    private Integer col148;
    private Integer col149;
    private Integer col150;
    private Integer col151;
    private Integer col152;
    private Integer col153;
    private Integer col154;
    private Integer col155;
    private Integer col156;
    private Integer col157;
    private Integer col158;
    private Integer col159;
    private Integer col160;
    private Integer col161;
    private Integer col162;
    private Integer col163;
    private Integer col164;
    private Integer col165;
    private Integer col166;
    private Integer col167;
    private Integer col168;
    private Integer col169;
    private Integer col170;
    private Integer col171;
    private Integer col172;
    private Integer col173;
    private Integer col174;
    private Integer col175;
    private Integer col176;
    private Integer col177;
    private Integer col178;
    private Integer col179;
    private Integer col180;
    private Integer col181;
    private Integer col182;
    private Integer col183;
    private Integer col184;
    private Integer col185;
    private Integer col186;
    private Integer col187;
    private Integer col188;
    private Integer col189;
    private Integer col190;
    private Integer col191;
    private Integer col192;
    private Integer col193;
    private Integer col194;
    private Integer col195;
    private Integer col196;
    private Integer col197;
    private Integer col198;
    private Integer col199;
    private Integer col200;

}
